### ISSUE TITLE
improve oar targets

### ISSUE THREAD

**Issue by lily-haas** [Virtual-Viking-Longship/Rowing-Minigame#21]

**Comment by lily-haas** [comment]
participants found the colorful oars confusing, make it more obvious they are not real by increasing transparency

**Comment by apjmason** [comment]
> participants found the colorful oars confusing, make it more obvious they are not real by increasing transparency

One thought on this, could you have only the brown oar visible at first and trigger the colorful pathway ones to appear only on success of grab action?

**Comment by lily-haas** [comment]
That's definitely something I could do with OpenXR so I assume the Oculus SDK has some way to do it. I'll start looking

**Comment by lily-haas** [comment]
https://communityforums.atmeta.com/t5/Unity-VR-Development/Check-if-an-object-is-grabbed/td-p/959742

Looks like easiest will be to detect if the hand is grabbing something

**Comment by lily-haas** [comment]
addressing this in another issue/branch
